/*
 * Demo catalogue.
 *
 * Used directly when no Supabase project is configured in config.js, and as a
 * fallback whenever a configured project is unreachable. Replace the entries
 * with your own, or point config.integrations.supabase at a project and this
 * file becomes the offline safety net.
 *
 * Yield and occupancy figures are indicative ranges for the region, not
 * guarantees attached to a specific title.
 */
window.RL_PROPERTIES = [
  {
    slug: 'villa-oceana',
    name: 'Villa Oceana',
    location: 'Cap Cana',
    price: '$4,200,000',
    tag: { en: 'Exclusive',
      fr: 'Exclusivité',
      es: 'Exclusiva' },
    beds: 6, baths: 7, sqm: 850,
    featured: true,
    lat: 18.5085, lng: -68.3734,
    year: 2023, lot: 2200, pool: { en: 'Infinity, 25 m',
      fr: 'À débordement, 25 m',
      es: 'Infinity, 25 m' }, parking: 4,
    img: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80&auto=format',
    gallery: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1600&q=82&auto=format'
    ],
    description: { en: 'The house sits on the coral shelf at the eastern edge of Cap Cana, about twelve metres above the water. It is a single storey wrapped around a central courtyard, and the living pavilion has been turned east so that the sea is in view from the kitchen and the pool terrace, and from both principal suites. Glass panels along the whole eastern face retract into the wall. For most of the year that leaves the living room and the terrace working as one room. Calacatta marble underfoot and ipe decking outside; the ironmongery is bronze throughout. The pool runs twenty-five metres along the edge of the terrace. Four of the six bedrooms are in a guest wing that has its own entrance and a service stair, which is useful if you intend to let the place and slightly odd if you do not. The plot is 2,200 m².',
      fr: 'La maison est posée sur le plateau corallien, à l’extrémité est de Cap Cana, à une douzaine de mètres au-dessus de l’eau. De plain-pied, organisée autour d’une cour centrale, avec le pavillon de vie tourné à l’est : la mer se voit depuis la cuisine, depuis la terrasse de la piscine et depuis les deux suites principales. Les panneaux vitrés de toute la façade est se rétractent dans le mur. La plus grande partie de l’année, le séjour et la terrasse ne font donc qu’une seule pièce. Marbre de Calacatta au sol, terrasse en ipé à l’extérieur ; la quincaillerie est en bronze partout. La piscine court sur vingt-cinq mètres le long de la terrasse. Quatre des six chambres occupent une aile d’invités avec son entrée et son escalier de service, ce qui est pratique si vous comptez louer et un peu curieux sinon. Le terrain fait 2 200 m².',
      es: 'La casa se asienta sobre la plataforma de coral, en el extremo este de Cap Cana, a unos doce metros sobre el agua. Es de una sola planta, dispuesta alrededor de un patio central, con el pabellón de estar orientado al este: el mar se ve desde la cocina, desde la terraza de la piscina y desde las dos suites principales. Los paneles de vidrio de toda la fachada este se recogen dentro del muro. Durante buena parte del año eso deja el salón y la terraza funcionando como una sola habitación. Mármol de Calacatta en el suelo, tarima de ipé fuera; los herrajes son de bronce en toda la casa. La piscina corre veinticinco metros a lo largo de la terraza. Cuatro de los seis dormitorios están en un ala de invitados con entrada propia y escalera de servicio, lo que viene bien si piensa alquilar y resulta algo extraño si no. La parcela es de 2.200 m².' },
    amenities: [
      { en: 'Infinity pool',
        fr: 'Piscine à débordement',
        es: 'Piscina infinity' },
      { en: 'Beach access',
        fr: 'Accès à la plage',
        es: 'Acceso a la playa' },
      { en: 'Screening room',
        fr: 'Salle de projection',
        es: 'Sala de cine' },
      { en: 'Wine store',
        fr: 'Cave à vin',
        es: 'Bodega' },
      { en: 'Spa and hammam',
        fr: 'Spa et hammam',
        es: 'Spa y hamam' },
      { en: 'Staff quarters',
        fr: 'Logement du personnel',
        es: 'Alojamiento del servicio' },
      { en: 'Gated, patrolled',
        fr: 'Résidence fermée et gardée',
        es: 'Cerrada y vigilada' },
      { en: 'Helipad',
        fr: 'Hélisurface',
        es: 'Helipuerto' }
    ],
    roi: { rentalYield: '8–12%', occupancyRate: '80%', projectedAppreciation: '6–8% p.a.', capRate: '7%' },
    confoturBenefits: { en: 'Confotur certified. Fifteen years exempt from transfer duty, annual property tax, rental income tax and capital gains tax.',
      fr: 'Certifié Confotur. Quinze ans d’exonération de droit de mutation, de taxe foncière annuelle, d’impôt sur les loyers et d’impôt sur la plus-value.',
      es: 'Certificada Confotur. Quince años de exención del impuesto de transferencia, del impuesto anual, del impuesto sobre alquileres y de la plusvalía.' },
    techSpecs: {
      construction: { en: 'Reinforced concrete frame, hurricane-rated glazing',
      fr: 'Ossature béton armé, vitrages classés cyclone',
      es: 'Estructura de hormigón armado, acristalamiento anticiclónico' },
      energy: { en: 'Solar-ready roof, Daikin VRV air conditioning',
      fr: 'Toiture pré-équipée solaire, climatisation Daikin VRV',
      es: 'Cubierta preparada para solar, climatización Daikin VRV' },
      water: { en: 'Reverse osmosis plant, 40,000 L cistern',
      fr: 'Unité d’osmose inverse, citerne de 40 000 L',
      es: 'Planta de ósmosis inversa, cisterna de 40.000 L' },
      smart: { en: 'Crestron control, Lutron lighting',
      fr: 'Pilotage Crestron, éclairage Lutron',
      es: 'Control Crestron, iluminación Lutron' },
      security: { en: 'Biometric entry, perimeter cameras, safe room',
      fr: 'Accès biométrique, caméras périmétriques, pièce forte',
      es: 'Acceso biométrico, cámaras perimetrales, habitación de pánico' }
    },
    conciergeServices: [
      { en: 'Chef placement',
        fr: 'Recrutement d’un chef',
        es: 'Selección de chef' },
      { en: 'Yacht charter',
        fr: 'Affrètement de yacht',
        es: 'Alquiler de yate' },
      { en: 'Airport fast-track',
        fr: 'Coupe-file à l’aéroport',
        es: 'Paso rápido en el aeropuerto' },
      { en: 'Property management',
        fr: 'Gestion du bien',
        es: 'Gestión de la propiedad' },
      { en: 'Housekeeping',
        fr: 'Ménage',
        es: 'Limpieza' },
      { en: 'Vehicle hire',
        fr: 'Location de voiture',
        es: 'Alquiler de vehículo' }
    ]
  },

  {
    slug: 'villa-palma',
    name: 'Villa Palma Real',
    location: 'Punta Cana',
    price: '$2,800,000',
    tag: { en: 'New build',
      fr: 'Neuf',
      es: 'Obra nueva' },
    beds: 5, baths: 5, sqm: 620,
    lat: 18.5601, lng: -68.3725,
    year: 2024, lot: 1800, pool: { en: 'Freeform lagoon',
      fr: 'Lagon de forme libre',
      es: 'Laguna de forma libre' }, parking: 3,
    img: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80&auto=format',
    gallery: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=82&auto=format'
    ],
    description: { en: 'Palma Real was finished at the start of 2024 and stands in a gated community about fifteen minutes from Punta Cana airport. The house is two blocks joined by a covered walkway, living and kitchen on one side, four bedrooms on the other, with a fifth room for staff off the service court. The pool is a shallow freeform lagoon edged in local coral stone, so anyone who wants to swim lengths will be disappointed. The kitchen is Spanish, with quartz worktops and a gas range. Planting is mature along all four boundaries and no neighbouring roof is visible from the ground floor.',
      fr: 'Palma Real a été livrée début 2024, dans une résidence fermée à un quart d’heure environ de l’aéroport de Punta Cana. La maison se compose de deux blocs reliés par une coursive couverte, séjour et cuisine d’un côté, quatre chambres de l’autre, avec une cinquième pièce pour le personnel donnant sur la cour de service. La piscine est un lagon peu profond de forme libre, bordé de pierre corallienne locale, de sorte que qui veut faire des longueurs sera déçu. La cuisine est espagnole, plans de travail en quartz et piano à gaz. Les plantations sont matures sur les quatre limites et aucun toit voisin n’est visible depuis le rez-de-chaussée.',
      es: 'Palma Real se terminó a principios de 2024 y está en un residencial cerrado a unos quince minutos del aeropuerto de Punta Cana. La casa son dos bloques unidos por un pasillo cubierto, salón y cocina en uno, cuatro dormitorios en el otro, con una quinta habitación para el servicio junto al patio de servicio. La piscina es una laguna poco profunda de forma libre, rematada en piedra de coral local, así que quien quiera nadar largos se llevará una decepción. La cocina es española, con encimeras de cuarzo y fogones de gas. La vegetación está crecida en los cuatro linderos y desde la planta baja no se ve ningún tejado vecino.' },
    amenities: [
      { en: 'Lagoon pool',
        fr: 'Piscine lagon',
        es: 'Piscina laguna' },
      { en: 'Mature gardens',
        fr: 'Jardins matures',
        es: 'Jardines maduros' },
      { en: 'Outdoor kitchen',
        fr: 'Cuisine d’été',
        es: 'Cocina exterior' },
      { en: 'Principal suite with terrace',
        fr: 'Suite principale avec terrasse',
        es: 'Suite principal con terraza' },
      { en: 'Gym',
        fr: 'Salle de sport',
        es: 'Gimnasio' },
      { en: 'Triple garage',
        fr: 'Garage triple',
        es: 'Garaje para tres coches' },
      { en: 'Staff room',
        fr: 'Chambre de personnel',
        es: 'Habitación de servicio' }
    ],
    roi: { rentalYield: '9–11%', occupancyRate: '78%', projectedAppreciation: '7–9% p.a.', capRate: '7%' },
    confoturBenefits: { en: 'Confotur certified under Law 158-01. Fifteen-year exemption; qualifies for the investor residency route.',
      fr: 'Certifié Confotur au titre de la loi 158-01. Exonération de quinze ans ; ouvre la voie de la résidence investisseur.',
      es: 'Certificada Confotur según la ley 158-01. Exención de quince años; da acceso a la residencia por inversión.' },
    techSpecs: {
      construction: { en: 'Insulated concrete forms, impact-rated windows',
      fr: 'Coffrages isolants, fenêtres anti-impact',
      es: 'Encofrados aislantes, ventanas antiimpacto' },
      energy: { en: 'Rooftop solar with battery storage',
      fr: 'Solaire en toiture avec stockage',
      es: 'Solar en cubierta con baterías' },
      water: { en: 'Well with mains backup, greywater recovery',
      fr: 'Puits avec appoint réseau, récupération des eaux grises',
      es: 'Pozo con apoyo de red, recuperación de aguas grises' },
      smart: { en: 'Control4 automation, multi-room audio',
      fr: 'Domotique Control4, audio multipièce',
      es: 'Domótica Control4, audio multisala' },
      security: { en: 'Gated community, private patrol, smart locks',
      fr: 'Résidence fermée, rondes privées, serrures connectées',
      es: 'Residencial cerrado, ronda privada, cerraduras inteligentes' }
    },
    conciergeServices: [
      { en: 'Tee-time booking',
        fr: 'Réservation de départs au golf',
        es: 'Reserva de salidas de golf' },
      { en: 'Spa and wellness',
        fr: 'Spa et bien-être',
        es: 'Spa y bienestar' },
      { en: 'Private dining',
        fr: 'Repas privés',
        es: 'Comidas privadas' },
      { en: 'Excursion planning',
        fr: 'Organisation d’excursions',
        es: 'Organización de excursiones' }
    ]
  },

  {
    slug: 'penthouse-marina',
    name: 'Penthouse Marina',
    location: 'Cap Cana',
    price: '$1,950,000',
    tag: { en: 'Sea view',
      fr: 'Vue mer',
      es: 'Vistas al mar' },
    beds: 4, baths: 4, sqm: 380,
    lat: 18.5120, lng: -68.3680,
    year: 2022, lot: 0, pool: { en: 'Roof plunge pool',
      fr: 'Bassin sur le toit',
      es: 'Piscina en la azotea' }, parking: 2,
    img: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80&auto=format',
    gallery: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1600&q=82&auto=format'
    ],
    description: { en: 'Top floor of a six-storey block on the northern quay, reached by a lift that opens into the flat rather than onto a landing. Main rooms face south-west over the moorings; the second bedroom and the study look inland across the golf course. The roof terrace is private and holds a plunge pool and an outdoor kitchen, with covered seating for ten, and the fifteen-metre berth included in the sale lies roughly sixty metres from the lobby door. Terrazzo floors throughout, motorised external blinds on the west elevation.',
      fr: 'Dernier étage d’un immeuble de six niveaux sur le quai nord, desservi par un ascenseur qui ouvre directement dans l’appartement et non sur un palier. Les pièces principales donnent au sud-ouest sur les pontons ; la seconde chambre et le bureau regardent vers l’intérieur, sur le golf. La terrasse de toit est privative et reçoit un bassin de nage et une cuisine d’été, avec un coin repas couvert pour dix, et l’anneau de quinze mètres compris dans la vente se trouve à une soixantaine de mètres de la porte du hall. Sols en terrazzo partout, stores extérieurs motorisés sur la façade ouest.',
      es: 'Última planta de un edificio de seis alturas en el muelle norte, con un ascensor que abre directamente al piso y no a un rellano. Las estancias principales miran al suroeste sobre los amarres; el segundo dormitorio y el despacho dan hacia el interior, al campo de golf. La azotea es privada y tiene piscina pequeña y cocina exterior, con zona de comedor cubierta para diez, y el amarre de quince metros incluido en la venta queda a unos sesenta metros de la puerta del portal. Suelos de terrazo en toda la vivienda, persianas exteriores motorizadas en la fachada oeste.' },
    amenities: [
      { en: 'Private roof terrace',
        fr: 'Terrasse de toit privative',
        es: 'Azotea privada' },
      { en: 'Plunge pool',
        fr: 'Bassin de nage',
        es: 'Piscina pequeña' },
      { en: 'Berth included',
        fr: 'Anneau compris',
        es: 'Amarre incluido' },
      { en: 'Private lift',
        fr: 'Ascenseur privatif',
        es: 'Ascensor privado' },
      { en: 'Concierge desk',
        fr: 'Conciergerie',
        es: 'Conserjería' },
      { en: 'Wine wall',
        fr: 'Mur à vin',
        es: 'Vinoteca' }
    ],
    roi: { rentalYield: '7–10%', occupancyRate: '75%', projectedAppreciation: '5–7% p.a.', capRate: '6%' },
    confoturBenefits: { en: 'Confotur certified. Short-let demand is steady year round given the marina frontage.',
      fr: 'Certifié Confotur. La demande en location courte durée est régulière toute l’année, grâce à la façade sur la marina.',
      es: 'Certificada Confotur. La demanda de alquiler de corta estancia es constante todo el año por su frente al puerto.' },
    techSpecs: {
      construction: { en: 'Steel frame, hurricane-rated curtain wall',
      fr: 'Ossature acier, mur-rideau classé cyclone',
      es: 'Estructura de acero, muro cortina anticiclónico' },
      energy: { en: 'Building solar array, individual metering',
      fr: 'Centrale solaire de l’immeuble, comptage individuel',
      es: 'Instalación solar del edificio, contadores individuales' },
      smart: { en: 'Savant control, motorised blinds',
      fr: 'Pilotage Savant, stores motorisés',
      es: 'Control Savant, persianas motorizadas' },
      security: { en: 'Staffed lobby, biometric lift, marina patrol',
      fr: 'Hall avec personnel, ascenseur biométrique, rondes sur la marina',
      es: 'Portería con personal, ascensor biométrico, vigilancia del puerto' }
    },
    conciergeServices: [
      { en: 'Berth management and provisioning',
        fr: 'Gestion de l’anneau et avitaillement',
        es: 'Gestión del amarre y aprovisionamiento' },
      { en: 'Diving and water sports',
        fr: 'Plongée et sports nautiques',
        es: 'Buceo y deportes náuticos' },
      { en: 'Marina club membership',
        fr: 'Adhésion au club de la marina',
        es: 'Membresía del club náutico' },
      { en: 'Helicopter transfers',
        fr: 'Transferts en hélicoptère',
        es: 'Traslados en helicóptero' },
      { en: 'Restaurant booking',
        fr: 'Réservation de restaurants',
        es: 'Reserva de restaurantes' }
    ]
  },

  {
    slug: 'domaine-samana',
    name: 'Domaine Samaná',
    location: 'Las Terrenas',
    price: '$5,500,000',
    tag: { en: 'Private estate',
      fr: 'Domaine privé',
      es: 'Finca privada' },
    beds: 8, baths: 9, sqm: 1200,
    lat: 19.3117, lng: -69.5396,
    year: 2021, lot: 8500, pool: { en: 'Two pools and a cenote',
      fr: 'Deux piscines et un cenote',
      es: 'Dos piscinas y un cenote' }, parking: 6,
    img: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80&auto=format',
    gallery: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600047509782-20d39509f26d?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=82&auto=format'
    ],
    description: { en: 'The plot is 8,500 m² and runs from the coast road down to a private stretch of sand on the northern side of the Samaná peninsula. The fall of the land sets the layout: nothing sits on one level and you walk a good deal. Accommodation is split across three buildings, a main house of five bedrooms and guest pavilions of two and one. At eight bedrooms and nine bathrooms that is closer to a small compound than a house, and it needs staff on the place year round. Construction is timber frame on stone bases with deep overhangs, and the living areas are cross-ventilated rather than air conditioned. The buildings date from 2021, so the timber has not had long to weather. A natural sinkhole on the lower terrace has been cleared and is used for swimming, and there are two pools besides. The land carries fruit trees and a working kitchen garden, both of which want looking after, and the caretaker’s cottage sits by the upper gate. There is a tennis court, and a private dock at the bottom of the land.',
      fr: 'Le terrain fait 8 500 m² et descend de la route côtière jusqu’à une plage de sable privée, sur le versant nord de la péninsule de Samaná. La pente commande l’implantation : rien n’est de plain-pied et l’on marche beaucoup. L’habitation se répartit sur trois bâtiments, une maison principale de cinq chambres et des pavillons d’invités de deux et une chambres. Avec huit chambres et neuf salles de bain, on tient davantage du petit hameau que de la maison, et il faut du personnel à demeure toute l’année. La construction est à ossature bois sur soubassements de pierre, avec de larges débords de toiture, et les pièces de vie sont ventilées naturellement plutôt que climatisées. Les bâtiments datent de 2021, le bois n’a donc pas encore beaucoup patiné. Un gouffre naturel sur la terrasse basse a été dégagé et sert de bassin de baignade, et il y a deux piscines par ailleurs. Le terrain porte des arbres fruitiers et un potager en activité, l’un et l’autre demandant de l’entretien, et la maison du gardien se tient près du portail haut. Il y a un court de tennis, et un ponton privé en bas du terrain.',
      es: 'La parcela tiene 8.500 m² y baja desde la carretera de la costa hasta un tramo de arena privado, en la vertiente norte de la península de Samaná. El desnivel manda en la distribución: nada queda a un mismo nivel y se camina bastante. El alojamiento se reparte en tres edificios, una casa principal de cinco dormitorios y pabellones de invitados de dos y uno. Con ocho dormitorios y nueve baños, esto se parece más a un pequeño conjunto que a una casa, y pide personal en la finca todo el año. La construcción es de estructura de madera sobre basamentos de piedra, con aleros profundos, y las zonas de estar se ventilan de forma cruzada en lugar de climatizarse. Los edificios son de 2021, así que la madera aún no ha tenido tiempo de envejecer. Un sumidero natural en la terraza baja se ha limpiado y se usa para bañarse, y además hay dos piscinas. El terreno tiene frutales y un huerto en producción, ambos piden cuidado, y la casa del guarda está junto al portón de arriba. Hay una pista de tenis y un muelle privado al final de la parcela.' },
    amenities: [
      { en: 'Private beach',
        fr: 'Plage privée',
        es: 'Playa privada' },
      { en: 'Two pools',
        fr: 'Deux piscines',
        es: 'Dos piscinas' },
      { en: 'Natural cenote',
        fr: 'Cenote naturel',
        es: 'Cenote natural' },
      { en: 'Guest pavilions',
        fr: 'Pavillons d’invités',
        es: 'Pabellones de invitados' },
      { en: 'Kitchen garden',
        fr: 'Potager',
        es: 'Huerto' },
      { en: 'Orchard',
        fr: 'Verger',
        es: 'Frutales' },
      { en: 'Private dock',
        fr: 'Ponton privé',
        es: 'Muelle privado' },
      { en: 'Tennis court',
        fr: 'Court de tennis',
        es: 'Pista de tenis' },
      { en: 'Caretaker’s cottage',
        fr: 'Maison de gardien',
        es: 'Casa del guarda' }
    ],
    roi: { rentalYield: '6–9%', occupancyRate: '70%', projectedAppreciation: '8–12% p.a.', capRate: '6%' },
    confoturBenefits: { en: 'Confotur certified. Las Terrenas remains the least built-out of the four corridors we cover.',
      fr: 'Certifié Confotur. Las Terrenas reste le moins urbanisé des quatre secteurs que nous couvrons.',
      es: 'Certificada Confotur. Las Terrenas sigue siendo el menos construido de los cuatro corredores que cubrimos.' },
    techSpecs: {
      construction: { en: 'Timber frame on stone bases',
      fr: 'Ossature bois sur soubassements de pierre',
      es: 'Estructura de madera sobre basamentos de piedra' },
      energy: { en: 'Off-grid solar with wind micro-turbine',
      fr: 'Solaire autonome avec micro-éolienne',
      es: 'Solar aislada con microaerogenerador' },
      water: { en: 'Spring supply and rainwater harvesting',
      fr: 'Alimentation par source et récupération des eaux de pluie',
      es: 'Suministro de manantial y recogida de agua de lluvia' },
      smart: { en: 'Deliberately minimal; satellite broadband',
      fr: 'Volontairement minimale ; internet par satellite',
      es: 'Deliberadamente mínima; internet por satélite' },
      security: { en: 'Private access road, resident manager, perimeter sensors',
      fr: 'Voie d’accès privée, régisseur sur place, détecteurs périmétriques',
      es: 'Camino de acceso privado, encargado residente, sensores perimetrales' }
    },
    conciergeServices: [
      { en: 'Guided walks with a naturalist',
        fr: 'Sorties guidées avec un naturaliste',
        es: 'Paseos guiados con un naturalista' },
      { en: 'Whale watching in season',
        fr: 'Observation des baleines en saison',
        es: 'Avistamiento de ballenas en temporada' },
      { en: 'Farm-to-table dining',
        fr: 'Table du potager',
        es: 'Comida de la huerta' },
      { en: 'Kite and surf instruction',
        fr: 'Cours de kite et de surf',
        es: 'Clases de kite y surf' },
      { en: 'Wellness programming',
        fr: 'Programme bien-être',
        es: 'Programa de bienestar' },
      { en: 'Boat days to Cayo Levantado',
        fr: 'Sorties en bateau à Cayo Levantado',
        es: 'Salidas en barco a Cayo Levantado' }
    ]
  },

  {
    slug: 'villa-coral',
    name: 'Villa Coral Bay',
    location: 'Bayahíbe',
    price: '$3,100,000',
    beds: 5, baths: 6, sqm: 720,
    lat: 18.3667, lng: -68.8333,
    year: 2023, lot: 3200, pool: { en: 'Infinity and jacuzzi',
      fr: 'À débordement et jacuzzi',
      es: 'Infinity y jacuzzi' }, parking: 3,
    img: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80&auto=format',
    gallery: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=82&auto=format',
      'https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=1600&q=82&auto=format'
    ],
    description: { en: 'Villa Coral Bay is built into the cliff above Bayahíbe, looking across at the marine reserve of the Parque Nacional del Este. It steps down the slope over three levels, so every room has an unbroken sea view and the roof of each level does duty as the terrace for the one above. A stair cut into the rock drops to a small private cove. Walls are local coral stone and poured concrete left exposed; the joinery is Caribbean cedar. The lowest level holds a studio with its own entrance, in use at the moment as a workshop. The arrangement does mean stairs between every level, and there are a lot of them. Plot is 3,200 m² and the garden is walled.',
      fr: 'Villa Coral Bay est encastrée dans la falaise au-dessus de Bayahíbe, face à la réserve marine du Parque Nacional del Este. Elle descend la pente sur trois niveaux, si bien que chaque pièce a une vue dégagée sur la mer et que la toiture de chaque niveau sert de terrasse à celui du dessus. Un escalier taillé dans la roche mène à une petite crique privée. Les murs sont en pierre corallienne locale et en béton coulé laissé brut ; les menuiseries sont en cèdre des Caraïbes. Le niveau le plus bas abrite un studio à entrée indépendante, occupé pour l’instant comme atelier. Le parti impose des escaliers entre chaque niveau, et ils sont nombreux. Le terrain fait 3 200 m² et le jardin est clos de murs.',
      es: 'Villa Coral Bay está encajada en el acantilado sobre Bayahíbe, frente a la reserva marina del Parque Nacional del Este. Baja la ladera en tres niveles, de modo que todas las estancias tienen vista despejada al mar y la cubierta de cada nivel hace de terraza para el de arriba. Una escalera tallada en la roca lleva a una pequeña cala privada. Los muros son de piedra de coral local y hormigón visto; la carpintería es de cedro caribeño. El nivel más bajo tiene un estudio con entrada independiente, ahora usado como taller. El planteamiento obliga a escaleras entre todos los niveles, y son muchas. La parcela es de 3.200 m² y el jardín está tapiado.' },
    amenities: [
      { en: 'Private cove',
        fr: 'Crique privée',
        es: 'Cala privada' },
      { en: 'Infinity pool',
        fr: 'Piscine à débordement',
        es: 'Piscina infinity' },
      { en: 'Cliff-edge jacuzzi',
        fr: 'Jacuzzi en bord de falaise',
        es: 'Jacuzzi al borde del acantilado' },
      { en: 'Three terraces',
        fr: 'Trois terrasses',
        es: 'Tres terrazas' },
      { en: 'Principal suite with dressing room',
        fr: 'Suite principale avec dressing',
        es: 'Suite principal con vestidor' },
      { en: 'Studio with separate entrance',
        fr: 'Studio à entrée indépendante',
        es: 'Estudio con entrada independiente' },
      { en: 'Open kitchen',
        fr: 'Cuisine ouverte',
        es: 'Cocina abierta' },
      { en: 'Walled garden',
        fr: 'Jardin clos de murs',
        es: 'Jardín tapiado' }
    ],
    roi: { rentalYield: '7–10%', occupancyRate: '72%', projectedAppreciation: '6–8% p.a.', capRate: '6%' },
    confoturBenefits: { en: 'Confotur eligible. The adjoining national park limits what can be built on the neighbouring plots.',
      fr: 'Éligible Confotur. Le parc national mitoyen limite ce qui peut être bâti sur les parcelles voisines.',
      es: 'Apta para Confotur. El parque nacional colindante limita lo que puede construirse en las parcelas vecinas.' },
    techSpecs: {
      construction: { en: 'Coral stone and reinforced concrete',
      fr: 'Pierre corallienne et béton armé',
      es: 'Piedra de coral y hormigón armado' },
      energy: { en: 'Solar array with mains backup',
      fr: 'Champ solaire avec appoint réseau',
      es: 'Instalación solar con apoyo de red' },
      water: { en: 'Desalination plant and rainwater capture',
      fr: 'Unité de dessalement et récupération des eaux de pluie',
      es: 'Planta desalinizadora y recogida de agua de lluvia' },
      smart: { en: 'KNX building control',
      fr: 'Gestion technique KNX',
      es: 'Control KNX del edificio' },
      security: { en: 'Cliff on one side, electronic gates, resident guard',
      fr: 'Falaise d’un côté, portails électroniques, gardien sur place',
      es: 'Acantilado en un lado, portones electrónicos, guarda residente' }
    },
    conciergeServices: [
      { en: 'Diving and snorkelling',
        fr: 'Plongée et masque-tuba',
        es: 'Buceo y esnórquel' },
      { en: 'Boat days to Saona',
        fr: 'Sorties en bateau à Saona',
        es: 'Salidas en barco a Saona' },
      { en: 'Marine reserve tours',
        fr: 'Visites de la réserve marine',
        es: 'Visitas a la reserva marina' },
      { en: 'Yoga on the terrace',
        fr: 'Yoga sur la terrasse',
        es: 'Yoga en la terraza' },
      { en: 'Private chef',
        fr: 'Chef à domicile',
        es: 'Chef privado' }
    ]
  }
];

/* Lifestyle tiles on the home page. */
window.RL_LIFESTYLE = [
  { title: { en: 'Golf',
      fr: 'Golf',
      es: 'Golf' }, sub: { en: 'Punta Espada, Corales, Teeth of the Dog',
      fr: 'Punta Espada, Corales, Teeth of the Dog',
      es: 'Punta Espada, Corales, Teeth of the Dog' }, img: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=900&q=80&auto=format' },
  { title: { en: 'Marinas',
      fr: 'Marinas',
      es: 'Puertos deportivos' }, sub: { en: 'Cap Cana, Casa de Campo, Samaná',
      fr: 'Cap Cana, Casa de Campo, Samaná',
      es: 'Cap Cana, Casa de Campo, Samaná' }, img: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=900&q=80&auto=format' },
  { title: { en: 'Restaurants',
      fr: 'Restaurants',
      es: 'Restaurantes' }, sub: { en: 'Playa Blanca, La Yola, Mitre',
      fr: 'Playa Blanca, La Yola, Mitre',
      es: 'Playa Blanca, La Yola, Mitre' }, img: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format' },
  { title: { en: 'Wellness',
      fr: 'Bien-être',
      es: 'Bienestar' }, sub: { en: 'Six Senses spa, Solaya, Bagua',
      fr: 'Spa Six Senses, Solaya, Bagua',
      es: 'Spa Six Senses, Solaya, Bagua' }, img: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=900&q=80&auto=format' }
];

/* Place names in the scrolling band between sections. */
window.RL_PLACES = [
  'Cap Cana', 'Punta Cana', 'Casa de Campo', 'Las Terrenas', 'Samaná',
  'Bayahíbe', 'La Romana', 'Puerto Plata', 'Cabarete', 'Sosúa'
];
